name: ci

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - "*"
  #     - "*/*"
  #     - "!master"
  # pull_request:
  #   branches:
  #     - "*"

env:
  CONTINAER_IMAGE_TAG: pr${{ github.event.pull_request.labels.name }}
  NODE_ENV: testing

jobs:
  build_artefacts:
    strategy:
      matrix:
        config:
          - { platform: linux, arch: amd64 }
          - { platform: linux, arch: arm64 }
          - { platform: windows, arch: 1809 }
          - { platform: windows, arch: ltsc2022 }
    runs-on: ubuntu-latest
    steps:
      - name: "[preparation] checkout the current branch"
        uses: actions/checkout@v3.5.3
      - name: "[preparation] set up golang 1.19.5"
        uses: actions/setup-go@v4.0.1
        with:
          go-version: "1.19.5"
      - name: "[preparation] set up node.js 18.x"
        uses: actions/setup-node@v2.5.2
        with:
          node-version: "18.x"
      - name: "[execution] Build Linux & Windows Portainer Binaries"
        run: |
          make build-server PLATFORM=${{ matrix.platform }} ARCH=${{ matrix.arch }} ENV=$(NODE_ENV)
          ls -latrh dist
      - name: "[post] Upload Artefact"
        uses: actions/upload-artifact@v3.1.2
        with:
          name: dist_${{ matrix.platform }}_${{ matrix.arch }}
          path: dist/portainer*
